"""Initial migration.

Revision ID: 06a232f51694
Revises: 
Create Date: 2020-09-17 11:12:24.412234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a232f51694'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_offers_status', table_name='trade_offers')
    op.drop_index('ix_trade_offers_time', table_name='trade_offers')
    op.drop_table('trade_offers')
    op.drop_index('ix_trade_orders_card_insurance', table_name='trade_orders')
    op.drop_index('ix_trade_orders_shipping_address', table_name='trade_orders')
    op.drop_index('ix_trade_orders_shipping_city', table_name='trade_orders')
    op.drop_index('ix_trade_orders_shipping_state', table_name='trade_orders')
    op.drop_index('ix_trade_orders_shipping_zip', table_name='trade_orders')
    op.drop_index('ix_trade_orders_time', table_name='trade_orders')
    op.drop_table('trade_orders')
    op.drop_index('ix_tradings_cardNumber', table_name='tradings')
    op.drop_index('ix_tradings_cardSeries', table_name='tradings')
    op.drop_index('ix_tradings_comments', table_name='tradings')
    op.drop_index('ix_tradings_for_trade', table_name='tradings')
    op.drop_index('ix_tradings_manufacturer', table_name='tradings')
    op.drop_index('ix_tradings_player_name', table_name='tradings')
    op.drop_index('ix_tradings_sport', table_name='tradings')
    op.drop_index('ix_tradings_time', table_name='tradings')
    op.drop_index('ix_tradings_tradeOrSell', table_name='tradings')
    op.drop_index('ix_tradings_username', table_name='tradings')
    op.drop_index('ix_tradings_year', table_name='tradings')
    op.drop_table('tradings')
    op.drop_index('ix_sales_cardNumber', table_name='sales')
    op.drop_index('ix_sales_cardSeries', table_name='sales')
    op.drop_index('ix_sales_comments', table_name='sales')
    op.drop_index('ix_sales_for_sale', table_name='sales')
    op.drop_index('ix_sales_manufacturer', table_name='sales')
    op.drop_index('ix_sales_player_name', table_name='sales')
    op.drop_index('ix_sales_price', table_name='sales')
    op.drop_index('ix_sales_sport', table_name='sales')
    op.drop_index('ix_sales_time', table_name='sales')
    op.drop_index('ix_sales_tradeOrSell', table_name='sales')
    op.drop_index('ix_sales_username', table_name='sales')
    op.drop_index('ix_sales_year', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_sale_orders_card_insurance', table_name='sale_orders')
    op.drop_index('ix_sale_orders_subtotal', table_name='sale_orders')
    op.drop_index('ix_sale_orders_time', table_name='sale_orders')
    op.drop_table('sale_orders')
    op.drop_table('offered_trades')
    op.drop_table('wanted_trades')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_time', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('wanted_sales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wanted_sales',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('sale_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
    sa.Column('email', sa.VARCHAR(length=32), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_time', 'users', ['time'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('wanted_trades',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('trade_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['tradings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('offered_trades',
    sa.Column('trade_id', sa.INTEGER(), nullable=True),
    sa.Column('trade_offer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['tradings.id'], ),
    sa.ForeignKeyConstraint(['trade_offer_id'], ['trade_offers.id'], )
    )
    op.create_table('sale_orders',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('subtotal', sa.INTEGER(), nullable=True),
    sa.Column('card_insurance', sa.BOOLEAN(), nullable=True),
    sa.Column('shipping_info', sa.BLOB(), nullable=True),
    sa.Column('billing_info', sa.BLOB(), nullable=True),
    sa.Column('time', sa.INTEGER(), nullable=True),
    sa.Column('item_ids', sa.BLOB(), nullable=True),
    sa.Column('item_owner_ids', sa.BLOB(), nullable=True),
    sa.Column('buyer_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('card_insurance IN (0, 1)'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_orders_time', 'sale_orders', ['time'], unique=False)
    op.create_index('ix_sale_orders_subtotal', 'sale_orders', ['subtotal'], unique=False)
    op.create_index('ix_sale_orders_card_insurance', 'sale_orders', ['card_insurance'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
    sa.Column('player_name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('sport', sa.VARCHAR(length=32), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=32), nullable=True),
    sa.Column('cardNumber', sa.VARCHAR(length=32), nullable=True),
    sa.Column('cardSeries', sa.VARCHAR(length=32), nullable=True),
    sa.Column('comments', sa.VARCHAR(length=32), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('tradeOrSell', sa.VARCHAR(length=32), nullable=True),
    sa.Column('time', sa.INTEGER(), nullable=True),
    sa.Column('img_paths', sa.BLOB(), nullable=True),
    sa.Column('for_sale', sa.BOOLEAN(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('for_sale IN (0, 1)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_year', 'sales', ['year'], unique=False)
    op.create_index('ix_sales_username', 'sales', ['username'], unique=False)
    op.create_index('ix_sales_tradeOrSell', 'sales', ['tradeOrSell'], unique=False)
    op.create_index('ix_sales_time', 'sales', ['time'], unique=False)
    op.create_index('ix_sales_sport', 'sales', ['sport'], unique=False)
    op.create_index('ix_sales_price', 'sales', ['price'], unique=False)
    op.create_index('ix_sales_player_name', 'sales', ['player_name'], unique=False)
    op.create_index('ix_sales_manufacturer', 'sales', ['manufacturer'], unique=False)
    op.create_index('ix_sales_for_sale', 'sales', ['for_sale'], unique=False)
    op.create_index('ix_sales_comments', 'sales', ['comments'], unique=False)
    op.create_index('ix_sales_cardSeries', 'sales', ['cardSeries'], unique=False)
    op.create_index('ix_sales_cardNumber', 'sales', ['cardNumber'], unique=False)
    op.create_table('tradings',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
    sa.Column('player_name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('sport', sa.VARCHAR(length=32), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=32), nullable=True),
    sa.Column('cardNumber', sa.VARCHAR(length=32), nullable=True),
    sa.Column('cardSeries', sa.VARCHAR(length=32), nullable=True),
    sa.Column('comments', sa.VARCHAR(length=32), nullable=True),
    sa.Column('tradeOrSell', sa.VARCHAR(length=32), nullable=True),
    sa.Column('time', sa.INTEGER(), nullable=True),
    sa.Column('img_paths', sa.BLOB(), nullable=True),
    sa.Column('for_trade', sa.BOOLEAN(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('wanted_in_return_card_ids', sa.BLOB(), nullable=True),
    sa.CheckConstraint('for_trade IN (0, 1)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tradings_year', 'tradings', ['year'], unique=False)
    op.create_index('ix_tradings_username', 'tradings', ['username'], unique=False)
    op.create_index('ix_tradings_tradeOrSell', 'tradings', ['tradeOrSell'], unique=False)
    op.create_index('ix_tradings_time', 'tradings', ['time'], unique=False)
    op.create_index('ix_tradings_sport', 'tradings', ['sport'], unique=False)
    op.create_index('ix_tradings_player_name', 'tradings', ['player_name'], unique=False)
    op.create_index('ix_tradings_manufacturer', 'tradings', ['manufacturer'], unique=False)
    op.create_index('ix_tradings_for_trade', 'tradings', ['for_trade'], unique=False)
    op.create_index('ix_tradings_comments', 'tradings', ['comments'], unique=False)
    op.create_index('ix_tradings_cardSeries', 'tradings', ['cardSeries'], unique=False)
    op.create_index('ix_tradings_cardNumber', 'tradings', ['cardNumber'], unique=False)
    op.create_table('trade_orders',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('card_insurance', sa.BOOLEAN(), nullable=True),
    sa.Column('shipping_address', sa.VARCHAR(), nullable=True),
    sa.Column('shipping_city', sa.VARCHAR(), nullable=True),
    sa.Column('shipping_state', sa.VARCHAR(), nullable=True),
    sa.Column('shipping_zip', sa.VARCHAR(), nullable=True),
    sa.Column('trade_offer_id', sa.INTEGER(), nullable=True),
    sa.Column('time', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('card_insurance IN (0, 1)'),
    sa.ForeignKeyConstraint(['trade_offer_id'], ['trade_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_orders_time', 'trade_orders', ['time'], unique=False)
    op.create_index('ix_trade_orders_shipping_zip', 'trade_orders', ['shipping_zip'], unique=False)
    op.create_index('ix_trade_orders_shipping_state', 'trade_orders', ['shipping_state'], unique=False)
    op.create_index('ix_trade_orders_shipping_city', 'trade_orders', ['shipping_city'], unique=False)
    op.create_index('ix_trade_orders_shipping_address', 'trade_orders', ['shipping_address'], unique=False)
    op.create_index('ix_trade_orders_card_insurance', 'trade_orders', ['card_insurance'], unique=False)
    op.create_table('trade_offers',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('offered_card_ids', sa.BLOB(), nullable=True),
    sa.Column('time', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('original_poster', sa.BLOB(), nullable=True),
    sa.Column('offerer_id', sa.INTEGER(), nullable=True),
    sa.Column('original_trade_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['offerer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_trade_id'], ['tradings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_offers_time', 'trade_offers', ['time'], unique=False)
    op.create_index('ix_trade_offers_status', 'trade_offers', ['status'], unique=False)
    # ### end Alembic commands ###
