"""new user field - seen_welcome_modal

Revision ID: c1c105a21b3f
Revises: 06a232f51694
Create Date: 2020-09-17 11:55:29.535737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c105a21b3f'
down_revision = '06a232f51694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('seen_welcome_modal', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_seen_welcome_modal'), 'users', ['seen_welcome_modal'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_seen_welcome_modal'), table_name='users')
    op.drop_column('users', 'seen_welcome_modal')
    # ### end Alembic commands ###
